[2025-03-25T10:33:31.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-25T10:33:31.595+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2025-03-17T00:00:00+00:00 [queued]>
[2025-03-25T10:33:31.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2025-03-17T00:00:00+00:00 [queued]>
[2025-03-25T10:33:31.606+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-25T10:33:31.622+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): inaccurate> on 2025-03-17 00:00:00+00:00
[2025-03-25T10:33:31.628+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T10:33:31.629+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2025-03-17T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpy2_ru6hn']
[2025-03-25T10:33:31.630+0000] {standard_task_runner.py:63} INFO - Started process 107 to run task
[2025-03-25T10:33:31.630+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask inaccurate
[2025-03-25T10:33:31.681+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2025-03-17T00:00:00+00:00 [running]> on host 7ed0592ccd5e
[2025-03-25T10:33:31.760+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T00:00:00+00:00'
[2025-03-25T10:33:31.762+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-25T10:33:31.773+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-25T10:33:31.774+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'accurate'"]
[2025-03-25T10:33:31.782+0000] {subprocess.py:86} INFO - Output:
[2025-03-25T10:33:31.784+0000] {subprocess.py:93} INFO - accurate
[2025-03-25T10:33:31.785+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-25T10:33:31.786+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-25T10:33:31.810+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=scheduled__2025-03-17T00:00:00+00:00, execution_date=20250317T000000, start_date=20250325T103331, end_date=20250325T103331
[2025-03-25T10:33:31.846+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-25T10:33:31.860+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T10:33:31.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
