[2025-03-17T20:08:12.813+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-17T20:08:12.841+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag._choose_best_model manual__2025-03-17T20:08:10.064598+00:00 [queued]>
[2025-03-17T20:08:12.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag._choose_best_model manual__2025-03-17T20:08:10.064598+00:00 [queued]>
[2025-03-17T20:08:12.853+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-17T20:08:12.875+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): _choose_best_model> on 2025-03-17 20:08:10.064598+00:00
[2025-03-17T20:08:12.882+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:08:12.884+0000] {standard_task_runner.py:63} INFO - Started process 279 to run task
[2025-03-17T20:08:12.885+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', '_choose_best_model', 'manual__2025-03-17T20:08:10.064598+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpeixmblxo']
[2025-03-17T20:08:12.887+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask _choose_best_model
[2025-03-17T20:08:12.953+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag._choose_best_model manual__2025-03-17T20:08:10.064598+00:00 [running]> on host 7ed0592ccd5e
[2025-03-17T20:08:13.052+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='_choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:08:10.064598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T20:08:10.064598+00:00'
[2025-03-17T20:08:13.053+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-17T20:08:13.068+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-17T20:08:13.080+0000] {python.py:237} INFO - Done. Returned value was: accurate
[2025-03-17T20:08:13.082+0000] {branch.py:36} INFO - Branch into accurate
[2025-03-17T20:08:13.083+0000] {skipmixin.py:178} INFO - Following branch accurate
[2025-03-17T20:08:13.104+0000] {skipmixin.py:246} INFO - Skipping tasks [('inaccurate', -1)]
[2025-03-17T20:08:13.136+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-17T20:08:13.159+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=_choose_best_model, run_id=manual__2025-03-17T20:08:10.064598+00:00, execution_date=20250317T200810, start_date=20250317T200812, end_date=20250317T200813
[2025-03-17T20:08:13.221+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-17T20:08:13.259+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T20:08:13.269+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
